name: Filmmakers Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes (stable)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4 deep-translator

      - name: Run script
        run: python script.py
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}

      - name: Save state
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add last.txt || true
          git commit -m "update last posts" || echo "no changes"
          git push
